homework_08/education/education/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('mysite.urls')),
    path('admin/', admin.site.urls),
]

homework_08/education/mysite/urls.py
from django.urls import path

from . import views
from .views import CoursesListView, CourseDetailView

app_name = "mysite"

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('courses/', CoursesListView.as_view(), name='courses'),
    path('course-details/<int:pk>/', CourseDetailView.as_view(), name="course-details"),
]

homework_08/education/mysite/models.py
from django.db import models


class CourseCategory(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    def __repr__(self):
        return f"<{self.__class__} #{self.pk} {self.name!r}>"


class Teacher(models.Model):
    name = models.CharField(max_length=255)
    avatar = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return self.name

    def __repr__(self):
        return f"<{self.__class__} #{self.pk} {self.name!r}>"


class Course(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.FloatField(null=True)
    views = models.PositiveSmallIntegerField(default=0)
    likes = models.PositiveSmallIntegerField(default=0)
    is_popular = models.BooleanField(default=False)
    category = models.ForeignKey(CourseCategory, on_delete=models.RESTRICT)
    teacher = models.ForeignKey(Teacher, on_delete=models.RESTRICT)

    def __str__(self):
        return self.name

    def __repr__(self):
        return f"<{self.__class__} #{self.pk} {self.name!r}>"

homework_08/education/mysite/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404
from django.http import HttpRequest

from .models import Course
from django.views.generic import ListView, DetailView, DeleteView, CreateView


def index(request: HttpRequest):
    popular_courses = Course\
        .objects\
        .select_related("category", "teacher")\
        .order_by("id")\
        .all()\
        .filter(is_popular=True)
    context = {
        "courses": popular_courses,
    }
    return render(request, "mysite/index.html", context=context)


def about(request: HttpRequest):
    context = {
        "page_title": "About Us",
        "white_header": True,
    }
    return render(request, "mysite/about-us.html", context=context)


def contact(request: HttpRequest):
    context = {
        "page_title": "Contact Us",
        "white_header": True,
    }
    return render(request, "mysite/contact.html", context=context)


def course_details(request: HttpRequest, pk: int):
    course = get_object_or_404(
        Course.objects.select_related("category", "teacher"),
        pk=pk,
    )
    context = {
        "page_title": course.name,
        "white_header": True,
        "course": course,
    }
    return render(request, "mysite/course-details.html", context=context)


class CoursesListView(ListView):
    # model = Animal
    queryset = Course.objects.select_related("category", "teacher").order_by("id").all()
    context_object_name = "courses"
    template_name = "mysite/courses.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_title"] = 'All courses'
        context["white_header"] = True
        return context


class CourseDetailView(DetailView):
    queryset = Course.objects.select_related("category", "teacher")
    template_name = "mysite/course-details.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_title"] = self.object.name
        context["white_header"] = True
        return context

homework_08/education/mysite/templates/mysite/_courses.html
<!--================ Start Popular Courses Area =================-->
<div class="popular_courses{% if white_header %} section_gap_top{% endif %}">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-5">
        <div class="main_title">
          <h2 class="mb-3">Our Popular Courses</h2>
          <p>
            Replenish man have thing gathering lights yielding shall you
          </p>
        </div>
      </div>
    </div>
    <div class="row">
      <!-- single course -->
      <div class="col-lg-12">
        <div class="owl-carousel active_course">
          {% for course in courses %}
          <div class="single_course">
            <div class="course_head">
              <img class="img-fluid" src="img/courses/c1.jpg" alt="" />
            </div>
            <div class="course_content">
              <span class="price">${{ course.price|floatformat:0 }}</span>
              <span class="tag mb-4 d-inline-block">{{ course.category.name }}</span>
              <h4 class="mb-3">
                <a href="{% url 'mysite:course-details' course.pk %}">{{ course.name }}</a>
              </h4>
              <p>{{ course.description }}</p>
              <div
                class="course_meta d-flex justify-content-lg-between align-items-lg-center flex-lg-row flex-column mt-4"
              >
                <div class="authr_meta">
                  <img src="img/courses/author1.png" alt="" />
                  <span class="d-inline-block ml-2">{{ course.teacher.name }}</span>
                </div>
                <div class="mt-lg-0 mt-3">
                  <span class="meta_info mr-4">
                    <a href="#"> <i class="ti-user mr-2"></i>{{ course.views }} </a>
                  </span>
                  <span class="meta_info"
                    ><a href="#"> <i class="ti-heart mr-2"></i>{{ course.likes }} </a></span
                  >
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>
<!--================ End Popular Courses Area =================-->

homework_08/education/mysite/templates/mysite/_footer.html
<!--================ Start footer Area  =================-->
<footer class="footer-area section_gap">
  <div class="container">
    <div class="row">
      <div class="col-lg-2 col-md-6 single-footer-widget">
        <h4>Top Products</h4>
        <ul>
          <li><a href="#">Managed Website</a></li>
          <li><a href="#">Manage Reputation</a></li>
          <li><a href="#">Power Tools</a></li>
          <li><a href="#">Marketing Service</a></li>
        </ul>
      </div>
      <div class="col-lg-2 col-md-6 single-footer-widget">
        <h4>Quick Links</h4>
        <ul>
          <li><a href="#">Jobs</a></li>
          <li><a href="#">Brand Assets</a></li>
          <li><a href="#">Investor Relations</a></li>
          <li><a href="#">Terms of Service</a></li>
        </ul>
      </div>
      <div class="col-lg-2 col-md-6 single-footer-widget">
        <h4>Features</h4>
        <ul>
          <li><a href="#">Jobs</a></li>
          <li><a href="#">Brand Assets</a></li>
          <li><a href="#">Investor Relations</a></li>
          <li><a href="#">Terms of Service</a></li>
        </ul>
      </div>
      <div class="col-lg-2 col-md-6 single-footer-widget">
        <h4>Resources</h4>
        <ul>
          <li><a href="#">Guides</a></li>
          <li><a href="#">Research</a></li>
          <li><a href="#">Experts</a></li>
          <li><a href="#">Agencies</a></li>
        </ul>
      </div>
      <div class="col-lg-4 col-md-6 single-footer-widget">
        <h4>Newsletter</h4>
        <p>You can trust us. we only send promo offers,</p>
        <div class="form-wrap" id="mc_embed_signup">
          <form
            target="_blank"
            action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
            method="get"
            class="form-inline"
          >
            <input
              class="form-control"
              name="EMAIL"
              placeholder="Your Email Address"
              onfocus="this.placeholder = ''"
              onblur="this.placeholder = 'Your Email Address'"
              required=""
              type="email"
            />
            <button class="click-btn btn btn-default">
              <span>subscribe</span>
            </button>
            <div style="position: absolute; left: -5000px;">
              <input
                name="b_36c4fd991d266f23781ded980_aefe40901a"
                tabindex="-1"
                value=""
                type="text"
              />
            </div>

            <div class="info"></div>
          </form>
        </div>
      </div>
    </div>
    <div class="row footer-bottom d-flex justify-content-between">
      <p class="col-lg-8 col-sm-12 footer-text m-0 text-white">
        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="ti-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
      </p>
      <div class="col-lg-4 col-sm-12 footer-social">
        <a href="#"><i class="ti-facebook"></i></a>
        <a href="#"><i class="ti-twitter"></i></a>
        <a href="#"><i class="ti-dribbble"></i></a>
        <a href="#"><i class="ti-linkedin"></i></a>
      </div>
    </div>
  </div>
</footer>
<!--================ End footer Area  =================-->

homework_08/education/mysite/templates/mysite/_header.html
{% load static %}

<!--================ Start Header Menu Area =================-->
<header class="header_area{% if white_header %} white-header{% endif %}">
  <div class="main_menu">
    <div class="search_input" id="search_input_box">
      <div class="container">
        <form class="d-flex justify-content-between" method="" action="">
          <input
            type="text"
            class="form-control"
            id="search_input"
            placeholder="Search Here"
          />
          <button type="submit" class="btn"></button>
          <span
            class="ti-close"
            id="close_search"
            title="Close Search"
          ></span>
        </form>
      </div>
    </div>

    <nav class="navbar navbar-expand-lg navbar-light">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <a class="navbar-brand" href="{% url 'mysite:index' %}">
        {% if not white_header %}
          <img src="{% static 'mysite/img/logo.png' %}" alt="" />
        {% else %}
          <img class="logo-2" src="{% static 'mysite/img/logo2.png' %}" alt="" />
        {% endif %}
        </a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="icon-bar"></span> <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div
          class="collapse navbar-collapse offset"
          id="navbarSupportedContent"
        >
          <ul class="nav navbar-nav menu_nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'mysite:index' %}">Home</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'mysite:about' %}">About</a>
            </li>
            <li class="nav-item submenu dropdown">
              <a
                href="#"
                class="nav-link dropdown-toggle"
                data-toggle="dropdown"
                role="button"
                aria-haspopup="true"
                aria-expanded="false"
                >Pages</a
              >
              <ul class="dropdown-menu">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'mysite:courses' %}">Courses</a>
                </li>
              </ul>
            </li>
            <li class="nav-item submenu dropdown">
              <a
                href="#"
                class="nav-link dropdown-toggle"
                data-toggle="dropdown"
                role="button"
                aria-haspopup="true"
                aria-expanded="false"
                >Blog</a
              >
              <ul class="dropdown-menu">
                <li class="nav-item">
                  <a class="nav-link" href="blog.html">Blog</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="single-blog.html"
                    >Blog Details</a
                  >
                </li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'mysite:contact' %}">Contact</a>
            </li>
            <li class="nav-item">
              <a href="#" class="nav-link search" id="search">
                <i class="ti-search"></i>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </div>
</header>
<!--================ End Header Menu Area =================-->

homework_08/education/mysite/templates/mysite/about-us.html
{% extends 'mysite/layout.html' %}

{% block body %}

    <!--================ Start About Area =================-->
    <section class="about_area section_gap">
      <div class="container">
        <div class="row h_blog_item">
          <div class="col-lg-6">
            <div class="h_blog_img">
              <img class="img-fluid" src="img/about.png" alt="" />
            </div>
          </div>
          <div class="col-lg-6">
            <div class="h_blog_text">
              <div class="h_blog_text_inner left right">
                <h4>Welcome to our Institute</h4>
                <p>
                  Subdue whales void god which living don't midst lesser
                  yielding over lights whose. Cattle greater brought sixth fly
                  den dry good tree isn't seed stars were.
                </p>
                <p>
                  Subdue whales void god which living don't midst lesser yieldi
                  over lights whose. Cattle greater brought sixth fly den dry
                  good tree isn't seed stars were the boring.
                </p>
                <a class="primary-btn" href="#">
                  Learn More <i class="ti-arrow-right ml-1"></i>
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!--================ End About Area =================-->

    <!--================ Start Feature Area =================-->
    <section class="feature_area section_gap_top title-bg">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-5">
            <div class="main_title">
              <h2 class="mb-3 text-white">Awesome Feature</h2>
              <p>
                Replenish man have thing gathering lights yielding shall you
              </p>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-4 col-md-6">
            <div class="single_feature">
              <div class="icon"><span class="flaticon-student"></span></div>
              <div class="desc">
                <h4 class="mt-3 mb-2">Scholarship Facility</h4>
                <p>
                  One make creepeth, man bearing theira firmament won't great
                  heaven
                </p>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6">
            <div class="single_feature">
              <div class="icon"><span class="flaticon-book"></span></div>
              <div class="desc">
                <h4 class="mt-3 mb-2">Sell Online Course</h4>
                <p>
                  One make creepeth, man bearing theira firmament won't great
                  heaven
                </p>
              </div>
            </div>
          </div>

          <div class="col-lg-4 col-md-6">
            <div class="single_feature">
              <div class="icon"><span class="flaticon-earth"></span></div>
              <div class="desc">
                <h4 class="mt-3 mb-2">Global Certification</h4>
                <p>
                  One make creepeth, man bearing theira firmament won't great
                  heaven
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!--================ End Feature Area =================-->

    <!--================ Start Testimonial Area =================-->
    <div class="testimonial_area section_gap">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-5">
            <div class="main_title">
              <h2 class="mb-3">Client say about me</h2>
              <p>
                Replenish man have thing gathering lights yielding shall you
              </p>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="testi_slider owl-carousel">
            <div class="testi_item">
              <div class="row">
                <div class="col-lg-4 col-md-6">
                  <img src="img/testimonials/t1.jpg" alt="" />
                </div>
                <div class="col-lg-8">
                  <div class="testi_text">
                    <h4>Elite Martin</h4>
                    <p>
                      Him, made can't called over won't there on divide there
                      male fish beast own his day third seed sixth seas unto.
                      Saw from
                    </p>
                  </div>
                </div>
              </div>
            </div>
            <div class="testi_item">
              <div class="row">
                <div class="col-lg-4 col-md-6">
                  <img src="img/testimonials/t2.jpg" alt="" />
                </div>
                <div class="col-lg-8">
                  <div class="testi_text">
                    <h4>Davil Saden</h4>
                    <p>
                      Him, made can't called over won't there on divide there
                      male fish beast own his day third seed sixth seas unto.
                      Saw from
                    </p>
                  </div>
                </div>
              </div>
            </div>
            <div class="testi_item">
              <div class="row">
                <div class="col-lg-4 col-md-6">
                  <img src="img/testimonials/t1.jpg" alt="" />
                </div>
                <div class="col-lg-8">
                  <div class="testi_text">
                    <h4>Elite Martin</h4>
                    <p>
                      Him, made can't called over won't there on divide there
                      male fish beast own his day third seed sixth seas unto.
                      Saw from
                    </p>
                  </div>
                </div>
              </div>
            </div>
            <div class="testi_item">
              <div class="row">
                <div class="col-lg-4 col-md-6">
                  <img src="img/testimonials/t2.jpg" alt="" />
                </div>
                <div class="col-lg-8">
                  <div class="testi_text">
                    <h4>Davil Saden</h4>
                    <p>
                      Him, made can't called over won't there on divide there
                      male fish beast own his day third seed sixth seas unto.
                      Saw from
                    </p>
                  </div>
                </div>
              </div>
            </div>
            <div class="testi_item">
              <div class="row">
                <div class="col-lg-4 col-md-6">
                  <img src="img/testimonials/t1.jpg" alt="" />
                </div>
                <div class="col-lg-8">
                  <div class="testi_text">
                    <h4>Elite Martin</h4>
                    <p>
                      Him, made can't called over won't there on divide there
                      male fish beast own his day third seed sixth seas unto.
                      Saw from
                    </p>
                  </div>
                </div>
              </div>
            </div>
            <div class="testi_item">
              <div class="row">
                <div class="col-lg-4 col-md-6">
                  <img src="img/testimonials/t2.jpg" alt="" />
                </div>
                <div class="col-lg-8">
                  <div class="testi_text">
                    <h4>Davil Saden</h4>
                    <p>
                      Him, made can't called over won't there on divide there
                      male fish beast own his day third seed sixth seas unto.
                      Saw from
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!--================ End Testimonial Area =================-->

{% endblock %}

homework_08/education/mysite/templates/mysite/contact.html
{% extends 'mysite/layout.html' %}

{% block body %}
    <!--================Contact Area =================-->
    <section class="contact_area section_gap">
      <div class="container">
        <div
          id="mapBox"
          class="mapBox"
          data-lat="40.701083"
          data-lon="-74.1522848"
          data-zoom="13"
          data-info="PO Box CT16122 Collins Street West, Victoria 8007, Australia."
          data-mlat="40.701083"
          data-mlon="-74.1522848"
        ></div>
        <div class="row">
          <div class="col-lg-3">
            <div class="contact_info">
              <div class="info_item">
                <i class="ti-home"></i>
                <h6>California, United States</h6>
                <p>Santa monica bullevard</p>
              </div>
              <div class="info_item">
                <i class="ti-headphone"></i>
                <h6><a href="#">00 (440) 9865 562</a></h6>
                <p>Mon to Fri 9am to 6 pm</p>
              </div>
              <div class="info_item">
                <i class="ti-email"></i>
                <h6><a href="#">support@colorlib.com</a></h6>
                <p>Send us your query anytime!</p>
              </div>
            </div>
          </div>
          <div class="col-lg-9">
            <form
              class="row contact_form"
              action="{% url 'mysite:contact' %}"
              method="post"
              id="contactForm"
              novalidate="novalidate"
            >
              <div class="col-md-6">
                <div class="form-group">
                  <input
                    type="text"
                    class="form-control"
                    id="name"
                    name="name"
                    placeholder="Enter your name"
                    onfocus="this.placeholder = ''"
                    onblur="this.placeholder = 'Enter your name'"
                    required=""
                  />
                </div>
                <div class="form-group">
                  <input
                    type="email"
                    class="form-control"
                    id="email"
                    name="email"
                    placeholder="Enter email address"
                    onfocus="this.placeholder = ''"
                    onblur="this.placeholder = 'Enter email address'"
                    required=""
                  />
                </div>
                <div class="form-group">
                  <input
                    type="text"
                    class="form-control"
                    id="subject"
                    name="subject"
                    placeholder="Enter Subject"
                    onfocus="this.placeholder = ''"
                    onblur="this.placeholder = 'Enter Subject'"
                    required=""
                  />
                </div>
              </div>
              <div class="col-md-6">
                <div class="form-group">
                  <textarea
                    class="form-control"
                    name="message"
                    id="message"
                    rows="1"
                    placeholder="Enter Message"
                    onfocus="this.placeholder = ''"
                    onblur="this.placeholder = 'Enter Message'"
                    required=""
                  ></textarea>
                </div>
              </div>
              <div class="col-md-12 text-right">
                <button type="submit" value="submit" class="btn primary-btn">
                  Send Message
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>
    <!--================Contact Area =================-->
{% endblock %}

homework_08/education/mysite/templates/mysite/courses.html
{% extends 'mysite/layout.html' %}

{% block title %}
    All courses
{% endblock %}

{% block body %}
    {% include 'mysite/_courses.html' with section_gap_top=1 %}
{% endblock %}

homework_08/education/mysite/templates/mysite/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="kk">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link rel="icon" href="{% static 'mysite/img/favicon.png' %}" type="image/png" />
    <title>
        {% block title %}
            Ali Education
        {% endblock %}
    </title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'mysite/css/bootstrap.css' %}" />
    <link rel="stylesheet" href="{% static 'mysite/css/flaticon.css' %}" />
    <link rel="stylesheet" href="{% static 'mysite/css/themify-icons.css' %}" />
    <link rel="stylesheet" href="{% static 'mysite/vendors/owl-carousel/owl.carousel.min.css' %}" />
    <link rel="stylesheet" href="{% static 'mysite/vendors/nice-select/css/nice-select.css' %}" />
    <!-- main css -->
    <link rel="stylesheet" href="{% static 'mysite/css/style.css' %}" />
  </head>

  <body>

    {% include 'mysite/_header.html' %}

    {% if white_header %}
        <!--================Home Banner Area =================-->
        <section class="banner_area">
          <div class="banner_inner d-flex align-items-center">
            <div class="overlay"></div>
            <div class="container">
              <div class="row justify-content-center">
                <div class="col-lg-6">
                  <div class="banner_content text-center">
                    <h2>{{ page_title }}</h2>
                    <div class="page_link">
                      <a href="{% url 'mysite:index' %}">Home</a>
                      <span>{{ page_title }}</span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <!--================End Home Banner Area =================-->
    {% endif %}

    {% block body %}
        Body block
    {% endblock %}

    {% include 'mysite/_footer.html' %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'mysite/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'mysite/js/popper.js' %}"></script>
    <script src="{% static 'mysite/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'mysite/vendors/nice-select/js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'mysite/vendors/owl-carousel/owl.carousel.min.js' %}"></script>
    <script src="{% static 'mysite/js/owl-carousel-thumb.min.js' %}"></script>
    <script src="{% static 'mysite/js/jquery.ajaxchimp.min.js' %}"></script>
    <script src="{% static 'mysite/js/mail-script.js' %}"></script>
    <!--gmaps Js-->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCjCGmQ0Uq4exrzdcL6rvxywDDOvfAu6eE"></script>
    <script src="{% static 'mysite/js/gmaps.min.js' %}"></script>
    <script src="{% static 'mysite/js/theme.js' %}"></script>
  </body>
</html>